name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: update
      run: sudo apt update
    - name: deps
      run: sudo apt install checkinstall libbsd-dev libmagic-dev libpng-dev libtiff-dev libxft-dev libxinerama-dev libxmu-dev libxpm-dev libxrandr-dev
    - name: script generation
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: checkinstall
      run: sudo checkinstall
