name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: update
      run: sudo apt update
    - name: deps
      run: sudo apt-get build-dep wmaker
    - name: script generation
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
